version: '3.8'
services:
  sandbox:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/bin/bash", "/opt/src/script/build.sh", "v1.1.2"]
    volumes:
      - "/mnt/windows/pgmodeler:/opt/pgmodeler"